spring:
  #404
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  datasource:
    #连接MySQL
    url: jdbc:mysql://localhost:3306/biao?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  typeAliasesPackage: com.biao.entity
  mapper-locations: classpath:mapper/*/*.xml
  configuration:
     #配置项：开启下划线到驼峰的自动转换. 作用：将数据库字段根据驼峰规则自动注入到对象属性。
     map-underscore-to-camel-case: true

   #打印SQL信息
logging:
  level:
   com:
    biao:
      controller: DEBUG
      dao: DEBUG





